---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
  namespace: openshift-operators
  labels:
    operators.coreos.com/kiali-ossm.openshift-operators: ""
spec:
  name: kiali-ossm
  channel: "stable"
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
