apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
    addons:
      grafana:
        enabled: true
      jaeger:
        install:
          ingress:
            enabled: true
          storage:
            memory:
              maxTraces: 100000
            type: Memory
        name: jaeger
      kiali:
        enabled: true
        name: kiali
      prometheus:
        enabled: true
    gateways:
      additionalEgress: {}
      egress:
        enabled: true
        namespace: istio-system
        runtime:
          container:
            resources:
              limits:
                cpu: 600m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
          deployment:
            autoScaling:
              enabled: false
            replicas: 1
            strategy:
              rollingUpdate:
                maxSurge: "1"
                maxUnavailable: "0"
              type: RollingUpdate
        service:
          ports:
          - name: https
            port: 443
            targetPort: 8443
          - name: http2-secure
            port: 9443
            targetPort: 9443
          - name: tcp-9444
            port: 9444
            targetPort: 9444
          - name: http2
            port: 80
            targetPort: 8080
          - name: status-port
            port: 15020
            targetPort: 15020
      ingress:
        runtime:
          container:
            resources:
              limits:
                cpu: 600m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
          deployment:
            autoScaling:
              enabled: false
            replicas: 1
        service:
          metadata:
            labels:
              gatewayType: ingress
              istio: ingressgateway
          ports:
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
          - name: tls
            port: 15443
            targetPort: 15443
          - name: status-port
            port: 15020
            targetPort: 15020
          type: ClusterIP
      openshiftRoute:
        enabled: false
    general:
      logging:
        componentLevels:
          default: info
      validationMessages: false
    policy:
      type: Istiod
    profiles:
    - default
    proxy:
      logging:
        level: info
      networking:
        trafficControl:
          inbound: {}
          outbound:
            policy: REGISTRY_ONLY
    runtime:
      components:
        pilot:
          container:
            resources:
              limits:
                cpu: "2"
                memory: 4Gi
              requests:
                cpu: 100m
                memory: 128Mi
          deployment:
            autoScaling:
              enabled: false
            replicas: 3
    security:
      controlPlane:
        mtls: true
      dataPlane:
        automtls: true
        mtls: true
    telemetry:
      type: Istiod
    tracing:
      sampling: 10000
      type: Jaeger
    version: v2.0